// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otzukwvudeucxbrrnhvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90enVrd3Z1ZGV1Y3hicnJuaHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1Nzc3OTQsImV4cCI6MjA2NjE1Mzc5NH0.jiqXBBOLS_KZGUtLvP90Tr4dCAEQXaqg_nZO_rH4Ty8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);